# ==========================================
# Konfigurasi Dashboard PTWDS News
# ==========================================

site:
  name: "PTWDS News"
  domain: "ptwdsnews.cloud"
  description: "PTWDS News Management System"

# Kredensial Login Admin (Catatan: Hindari password sederhana di tahap produksi)
admin:
  email: "admin@ptwdsnews.cloud"
  password: "admin"

# Konfigurasi Database (Google Apps Script)
api:
  script_url: "https://script.google.com/macros/s/AKfycbxK03aPFxnWadssqlubzoxidW_78cPUBJC0z0rttRg_3ItBGBsP42XhhZpZxSJysOrZ2w/exec"

# Konfigurasi Upload Gambar (ImageKit.io)
imagekit:
  public_key: "public_GDQUCyVsO4E4swVuMvRzBQy51zk="
  url_endpoint: "https://ik.imagekit.io/ptwdsnewscloud/artikel/"
